//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.03 at 02:28:27 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/spring/ws/groups", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.example.example_soap.soap.groups;
